### PR TITLE
Index trackExistence is true by default Fixes #1637

### LINKED ISSUE #1637: [proposal] enable trackExistence by default
### Description

I think that we should seriously consider enabling trackExistence by default for new indexes before we cut a new release. This won't strictly be a breaking change, but will reduce performance somewhat for imports. My concern is that new users will create an index with the default option, and then get frustrated when the `Not` query, and any other functionality which depends on existence is not available to them. I also have an inkling more functionality will depend on existence in the future, and existing users won't be able to take advantage of it unless they've specifically enabled it in the past whether they needed it at the time or not.

### Success criteria (What criteria will consider this ticket closeable?)
We've discussed enabling trackExistence by default, made a decision, and implemented it.

### PR DESCRIPTION
**Pull request by yuce**
## Overview

Fixes #1637 

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by travisturner** [comment]
I would expect the default logic to be defined in the `pilosa` package (I get that it may also need to be in the `http` package, but having it confined there is not really enforcing a default). 

I think at the very least the instance of `Index` that is returned by `NewIndex()` should have:
```trackExistence: true,```

**Comment by travisturner** [comment]
I don't love the potential double negative that comes with renaming this option to `DisableTrackExsistence`, but in this case maybe that's the right thing to do since having the default be `false` is cleaner.

Anyone have any opinions on that?

**Comment by jaffee** [comment]
I think we should prioritize making the option read more intuitively at the cost of some implementation complexity for us. That is to say, I prefer trackExistence over disableExistenceTracking. 

Most of our existing boolean options already follow this pattern `verbose`, `coordinator`, `diagnotics`, `keys`. The only one I see that doesn't is `tls-skip-verify`.

**Comment by yuce** [comment]
@travisturner I've pushed a commit that sets `trackExistence `in `NewIndex`.

**Pull request merged**
