### PR TITLE
Ensure btree comparison doesn't fail for smallish N

### PR DESCRIPTION
**Pull request by seebs**
## Overview

 enterprise/b: Ensure 64-bit range for btree keys.

The cmp() function used to compare btree keys was using the
trick of comparing unsigned values by coercing the result
of subtraction to a signed type. This is fine as long as
the range of differences never actually exceeds the limits
of the signed type. For instance, with int64, as long as
the magnitude of the difference is under 2^63 or so, it
works reasonably well.

Plain int, however, can be a 32-bit type, at which point
the magnitude of difference needed to break it is only
2^31 or so.

Subtraction and type conversion is enough cheaper than
branches that this is worth preserving, but it's worth
preserving by switching to an explicit int64 for the
operation and return type. This will not actually affect
performance except for people using the btree code on
32-bit machines, so it probably won't ever matter.
Which may also be true of the potential wrong answers,
but "might be slower" is a better risk than "might
crash".

## Pull request checklist

- [X] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [X] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [X] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [X] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [X] All new and existing tests pass.

Haven't written a test for this. Possibly I should; this is the kind of thing that'd be worth having test cases for, perhaps.

Not sure whether this change is substantive enough to need to be in the docs.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by travisturner** [comment]
@seebs can you make this two separate PRs? I can review the b+tree portion, but I'd like @codysoyland to look at the handler changes.

**Comment by codysoyland** [comment]
FYI, the handler changes are duplicated from #1711, so after that is merged, this PR will only contain the btree changes. I would just suggest creating a more descriptive title and description.

**Comment by seebs** [comment]
I... totally thought I had successfully used the github UI today. I guess not. Will fix that up.

**Comment by seebs** [comment]
did i seriously just paste in the header from the WRONG commit? why, yes, yes i did. this is me before breakfast and caffeine.

**Pull request merged**
