### PR TITLE
docker-micro target

### PR DESCRIPTION
**Pull request by yuce**
* I've added the slim container target. The `Dockerfile` and build script is in `docker-micro` in order to not pollute the project root. Do you think that's a good idea ?
* The build container target downloads a prebuilt glide but checks its sha256 hash.
* There was a problem with the version of the generated pilosa binary. This PR fixes that as welll.

### CODE REVIEW

**Comment by codysoyland** [comment]
Hey @yuce, apologies for the delay on reviewing this. Could you resolve the makefile conflicts and re-push when you get a chance? I will make sure we get this in shortly. Thanks man!!!

**Comment by codysoyland** [comment]
Also @yuce could you please sign the CLA? https://cla-assistant.io/pilosa/pilosa

**Comment by yuce** [comment]
@codysoyland Do you mind if I create a new PR with the same changes? Due to the private -> public change my pilosa repo became a bit wonky.

**Comment by codysoyland** [comment]
Totally cool @yuce !

**Pull request closed without merging**
