### PR TITLE
 holder.go: fix some logic errors

### PR DESCRIPTION
**Pull request by sundy-li**
## Overview

[Describe what this pull request addresses.]

- Remove the `h.hasV1TranslateKeysFile`, because it's not correct.

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [x] All new and existing tests pass.
- [x] Make sure PR title conforms to convention in CHANGELOG.md.
- [x] Add appropriate changelog label to PR (if applicable).

### CODE REVIEW

**Comment by kuba--** [comment]
@sundy-li - Thanks for the PR. I've re-ran CI, but could you take a look into the failing test:
```
--- FAIL: TestAPI_Import (1.11s)
    --- FAIL: TestAPI_Import/RowKeyColumnID (0.24s)
        api_test.go:179: executing: translate store could not find or create key, translate store read only
```

**Comment by sundy-li** [comment]
@kuba--   I just force update this pr. Seems all tests are passed.

This PR just removes `hasV1TranslateKeysFile` function, because it returns true if path not exists, which is not behaving as the comment. And this function is useless because we may never V1 translate file, and it will throw errors.

```
// hasV1TranslateKeysFile returns true if a v1 translation data file exists on disk.	
func (h *Holder) hasV1TranslateKeysFile() (bool, error) {	
	if _, err := os.Stat(filepath.Join(h.Path, ".keys")); os.IsNotExist(err) {	
		return true, nil
```

**Comment by kuba--** [comment]
@sundy-li , could you sign CLA, so I'll be able to merge it.

**Comment by sundy-li** [comment]
> @sundy-li , could you sign CLA, so I'll be able to merge it.

done

**Pull request merged**
