### PR TITLE
Implements view import

### PR DESCRIPTION
**Pull request by yuce**
## Overview

This PR adds support for importing raw views. This is required to be able to import data exported by `/export` endpoint. I've modified `ImportRequest` protobuf message to carry a `View` field, but I can add it as a query arg too in case changes to the protobuf code is not desired.

`/import` endpoint is not publicly documented.

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by yuce** [comment]
Added the tests; this PR should be OK to review.

**Comment by yuce** [comment]
PING

**Comment by travisturner** [comment]
@yuce can you provide me with an example where this applies so i can understand the use case and help test it.

**Comment by yuce** [comment]
@travisturner The main reason this is needed is, exporting bits (`/export` endpoint) requires a view and returns `row_id, column_id` for each bit. Importing bits on the other hand (`/import`) requires a frame and `row_id,column_id[,timestamp]` so exported data cannot be used for imports. This PR implements the missing *view* bit, so the user can export bits for a view and import the same data.

**Comment by travisturner** [comment]
@yuce i guess i'm trying to understand which view would typically be specified for an import. I don't think it makes sense to specify `inverse` because an inverse view is going to be automatically created/populated when you import data from the `standard` view (we would have to suppress that functionality on `standard` import if we wanted to specifically handle `inverse` view population via an import. The other views are related to time quantums. Is that what you're trying to address here?

**Comment by yuce** [comment]
I didn't notice the inverse view would be automatically created on import. We should have a way to suppress that. Yes, we should import time quantum views explicitly or update `/export` endpoint so it returns timestamps.

**Comment by yuce** [comment]
Having said that, I think the ability to import views is a more future-proof solution; in case we have different kinds of views in the future.

**Comment by jaffee** [comment]
closing for now - referenced in #888

**Pull request closed without merging**
