### PR TITLE
Cancel queries on Context.Done()

### LINKED ISSUE #1745: Query Cancellation
### Description

Currently we are propagating contexts throughout our stack, but once a query has been kicked off, there's no way to cancel it early. This becomes an issue if a client executes an extremely complex query (think Union of 200,000 rows), and then gives up before the query completes. The Pilosa cluster may remain loaded by the query for quite some time. Pilosa executors should periodically check the context and be able to exit early from queries, gracefully unlocking any locks, cleaning up goroutines, releasing memory, etc.

### Success criteria (What criteria will consider this ticket closeable?)
Queries can be cancelled.

### PR DESCRIPTION
**Pull request by benbjohnson**
## Overview

This commit periodicially checks if the context has been cancelled
or if a deadline has been reached. If so, it returns a query-related
error message depending on the cause.

Fixes #1745

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [x] I have resolved any merge conflicts.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by benbjohnson** [comment]
@jaffee The `validateQueryContext()` is executed inside `executor.executeCall()` so it checks on nested calls as well. I tested it against a `Union()` with a ton of child calls (not sure if it was 50K but it was a lot) and it successfully cancels.

Do you have an example query that's not canceling?

**Comment by jaffee** [comment]
@benbjohnson 	AFAICT, executor.executeCall is only called on top level queries and queries inside of an `Options` call. I feel like I must be missing something obvious, but I can't see how a call like: `Union(Row(afield=1), Row(afield=2), Row(afield=3)..., Row(afield=9999))` could be interrupted once it gets into executor.executeUnionShard

My very unscientific test was to launch one of these ridiculous super-Union queries from our taxi-demo and then kill the demo server and observe whether the load on Pilosa dropped or continued - my understanding is that if the connection dies the http server will cancel the context.

**Comment by benbjohnson** [comment]
@jaffee Ah, you're totally right. I was executing a large query then waiting a few seconds and canceling but the query was so large it was still in the parse phase so it caught the cancel before execution.

I went through and checked all `pql.Call.Children` usage in `executor` and it looks like just the `executeBitmapCallShard()` needed a check added in order to catch them all. I did some more testing and verified that it cancels once it's in the execution phase. `/facepalm`

**Comment by jaffee** [comment]
so what you're saying is, if our darn parser wasn't so slow...   ;)

This totally works though! Very cool to see the load drop immediately after killing the client. Thanks!

**Comment by jaffee** [comment]
I'm going to go ahead and merge this as long as all checks are passing and it's up to date with the base branch.

**Pull request merged**
