### PR TITLE
fix overflow in differenceRunBitmap

### LINKED ISSUE #939: range query out of memory
I have a benchmark of pilosa range query.
[pilosa_range_bench.go.txt](https://github.com/pilosa/pilosa/files/1453566/pilosa_range_bench.go.txt)

It inserts 1M documents into bitmap, then query. The insertion phase costs about 90s. At query phase, it crash due to out-of-memory.

My laptop is running Linux Mint 18.2, amd64, 8GB RAM + 8GB Swap.

GC log indicates heap keeps increasing:

```
gc 12398 @119.833s 1%: 0.007+2404+0.099 ms clock, 0.058+0.043/0.40/2404+0.79 ms cpu, 2872->2872->2119 MB, 3391 MB goal, 8 P
gc 12399 @124.688s 1%: 0.008+4985+0.087 ms clock, 0.067+0.14/0.078/4985+0.70 ms cpu, 5429->5429->3310 MB, 5430 MB goal, 8 P
gc 12400 @129.720s 1%: 23+7088+0.14 ms clock, 185+0.16/1.9/7186+1.1 ms cpu, 5609->5609->4138 MB, 6621 MB goal, 8 P
scvg0: inuse: 7014, idle: 1201, sys: 8216, released: 0, consumed: 8216 (MB)

```

Memory profile indicates almost all heap space is allocated by a single line.

```
(pprof) list RunBitmap
Total: 3.23GB
ROUTINE ======================== github.com/pilosa/pilosa/roaring.differenceRunBitmap in /home/zhichyu/src/github.com/pilosa/pilosa/roaring/roaring.go
    3.23GB     3.23GB (flat, cum)   100% of Total
         .          .   2523:				} else if bit == run.last {
         .          .   2524:					run.last--
         .          .   2525:				} else {
         .          .   2526:					run.last = bit - 1
         .          .   2527:					if run.last >= run.start {
    3.23GB     3.23GB   2528:						output.runs = append(output.runs, run)
         .          .   2529:					}
         .          .   2530:					run.start = bit + 1
         .          .   2531:					run.last = a.runs[j].last
         .          .   2532:				}
         .          .   2533:				if run.start > run.last {
(pprof) 

```

I have patched pilosa with following diff to resolve a segment fault:
```
diff --git a/roaring/roaring.go b/roaring/roaring.go
index 62f87d9..c05d9e6 100644
--- a/roaring/roaring.go
+++ b/roaring/roaring.go
@@ -2508,7 +2508,7 @@ func differenceRunArray(a, b *container) *container {
 // differenceRunBitmap computes the difference of an run from a bitmap.
 func differenceRunBitmap(a, b *container) *container {
        // If a is full, difference is the flip of b.
-       if a.runs[0].start == 0 && a.runs[0].last == 65535 {
+       if len(a.runs) > 0 && a.runs[0].start == 0 && a.runs[0].last == 65535 {
                return b.flipBitmap()
        }
        output := &container{container_type: ContainerRun}


```

pilosa revision:
```
zhichyu@wonder:~/src/github.com/pilosa/pilosa$ git log
commit bbc82d166dad8c3d033f8b46d37553ec02dea44a
Merge: 17da044 64da894
Author: Michael Baird <raskle@yahoo.com>
Date:   Tue Nov 7 10:12:56 2017 -0600

```

### PR DESCRIPTION
**Pull request by tgruben**
corrected for the issue when a run ended in maxuint16

Fixes #939

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [x] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by travisturner** [comment]
This looks like the same fix we put in place in `intersectBitmapRun()`.
Are there any other cases like this?

**Comment by travisturner** [comment]
see cf372cdd1d08158201c1e24c9857f8a6a2c2c028

**Comment by travisturner** [comment]
@tgruben I don't quite understand the `add` logic that you've added. 
Also, assume the first overflow check that you've added (line 2526) is for the case where there is a single-bit run in the last bit position? Can you update the tests to include the cases that you're handling?

**Comment by tgruben** [comment]
the bug was isolated to a single bit run at the last bit @travisturner

**Comment by alanbernstein** [comment]
I see one potential overflow problem in `differenceRunIterator` at `vr.start++`, but we're no longer using that function. Does anyone want to keep that? @jaffee

**Comment by jaffee** [comment]
it's not exported, so if it isn't called anywhere from within the package, remove it. I suspect that it's called in a test, in which case we just need to make sure the correct results are enforced in the tests and then remove it.

**Pull request merged**
