### PR TITLE
Uip time only

### PR DESCRIPTION
**Pull request by jaffee**
## Overview

Use UnionInPlace when computing time rows which involve multiple views. Decreases memory allocation immensely.

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Add appropriate changelog label to PR (if applicable).

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Make sure PR is tagged with appropriate changelog label.

### CODE REVIEW

**Comment by jaffee** [comment]
we should actually get this merged, I think it's safe for general consumption. @seebs do you want to take another pass at that merge logic now that we have some time to breathe, or is this OK for a more thorough review and merge?

**Comment by seebs** [comment]
Honestly, I think I'm okay with the slightly-inefficient merge logic. We could probably make it saner by extracting-and-sorting the complete list of segment keys, but I think in practice it wouldn't be *much* saner, and the current version is Obviously Correct.

It'd be possible to skip one step, sort of, by computing next iteration's shard key as a side-effect of the current loop, but the cost of computing the shard keys seems likely to be small, especially since I'm pretty sure the only call this actually gets ever has N=1.

**Comment by jaffee** [comment]
You mentioned at one point that there might be one level of abstraction too many here, and I think I agree with you. Let's get this merged, but not lose that thought... I think we could refactor and simplify.

**Comment by jaffee** [comment]
I would approve this, but I can't since I made the PR (even though it's Seebs' commits)

**Pull request merged**
