### PR TITLE
Adds Open File Limit Support for Administration section of Pilosa Docs

### PR DESCRIPTION
**Pull request by asvetlik**
## Overview

I added the information I learned from having to reset my Open File Limit on my Mac to the Administration doc.

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [x] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [ ] All new and existing tests pass.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Add appropriate changelog label to PR (if applicable).

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Make sure PR is tagged with appropriate changelog label.

### CODE REVIEW

**Comment by asvetlik** [comment]
The last line of the Data-Model.md file is the EXACT same but it is saying they are different.

**Comment by travisturner** [comment]
@asvetlik when you see that it usually means that a line feed was either added or removed. Text editors seem to have different default behaviors when it comes to line feeds. If you look at the diff with git you'll see:
```
diff --git a/docs/data-model.md b/docs/data-model.md
index 86b0111..7de27b5 100644
--- a/docs/data-model.md
+++ b/docs/data-model.md
@@ -202,4 +202,4 @@ Mutex fields are similar to `set` fields, with the distinction of requiring the

 #### Boolean

-A boolean field is similar to a `mutex` field tracking only two values: `true` and `false`. Boolean fields do not maintain a sorted cache, nor do they support key values.
\ No newline at end of file
+A boolean field is similar to a `mutex` field tracking only two values: `true` and `false`. Boolean fields do not maintain a sorted cache, nor do they support key values.
```
(notice the `\ No newline at end of file` comment)

**Comment by asvetlik** [comment]
@travisturner That was so weird. In VSCode, there wasn't a line at the end of the file, but when I did `nano data-model.md`, there was a line

**Comment by asvetlik** [comment]
The commit history is very messy and could potentially cause problems later on. I will fix and recreate pull request.

**Pull request closed without merging**
