### PR TITLE
Adds --field-keys and --index-keys options to pilosa import

### LINKED ISSUE #1570: pilosa import --create doesn't use --string-keys
For bugs, please provide the following:

### Expected behavior

`./pilosa import --create --string-keys --index i1 --field f1 CSV_FILE` should create `i1` and `f1` with `keys=true`.

### Actual behavior

Running the following:
```
curl localhost:10101/index/i1/query -d 'Row(f1="foo")'
```

Results in:
```
{"error":"executing: string 'row' value not allowed unless field 'keys' option enabled"}
```
### Steps to reproduce the behavior
```
./pilosa import --create --index i1 --field f1 --string-keys 1.csv
```
With the following CSV:
```
foo,bar
```
Then:
```
curl localhost:10101/index/i1/query -d 'Row(f1="foo")'
```

### PR DESCRIPTION
**Pull request by yuce**
## Overview

* I had to add `client.CreateFieldWithOptions` and `client.EnsureFieldWithOptions` functions in order to be able to pass create a field with options.
* `client.CreateFieldWithOptions` takes a `pilosa.FieldOptions` argument, but `http.postFieldRequest` requires the options as `http.fieldOptions`. Had to  convert from the former to the latter. I had to set different fields depending on the type of the field, since e.g., setting `Min` or `Max` is invalid for `set` fields (I'm happy that the tests cover that)
* I had to use `--index-keys` and `--field-keys` since `--index.keys` and `--field.keys` makes a few tests fail
* I didn't remove `--string-keys`. Should I ?

Fixes #1570

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by jaffee** [comment]
was `--string-keys` broken before 1.0? If so, I think we can safely remove it. If it was functional at 1.0, we need to preserve that functionality though

**Comment by jaffee** [comment]
what exactly was the problem with index.keys and field.keys? My thought was that we'd export the `FieldOptions` and `IndexOptions` attributes to the command struct then create a flag for each option which populates the option struct. e.g.
```go
flags.BoolVar(&Importer.FieldOptions.Keys, "field.keys", false, "use keys=true when creating a field")
flags.IntVar(&Importer.FieldOptions.Min, "field.min", 0, "use a minimum of 0 when creating an int field")
```

**Comment by yuce** [comment]
Honestly I didn't try making `--index.keys` before, since `--index-keys` worked fine, but below are the errors:
```
--- FAIL: TestImportConfig (0.00s)
	root_test.go:121: Problem with test 0, err: 'strconv.ParseBool: parsing "": invalid syntax'
--- FAIL: TestInspectNoPath (0.00s)
	inspect_test.go:33: Command 'inspect' without args should error but: err: 'invalid option in configuration file: index', output: ''
--- FAIL: TestInspectMultiPath (0.00s)
	inspect_test.go:40: Command 'inspect' without args should error but: err: 'invalid option in configuration file: index', output: ''
```
When I have this:
```
flags.BoolVar(&Importer.IndexOptions.Keys, "index.keys", false, "use keys=true when creating an index")
```
It seems like it doesn't like `index` in the option name. When I change it to `indx` there are no errors.

**Comment by yuce** [comment]
I think `--string-keys` was initially used to tell to use interpret the CSV as string rows and columns. It didn't work when creating the schema (hence https://github.com/pilosa/pilosa/issues/1570). There's a comment in `ctl/import.go` about line 53: `TODO: remove this in a future release` so I think we can just remove it.

**Comment by jaffee** [comment]
seems safe to me

**Comment by yuce** [comment]
OK, removed `--string-keys`.

**Comment by jaffee** [comment]
ah, I see the issue - because index is already a flag on its own we can't nest anything under it - because of how it behaves if you use a config file

**Pull request merged**
