### PR TITLE
WIP: Support staticcheck.

### PR DESCRIPTION
**Pull request by seebs**
## Overview

WIP: Add support for staticcheck. Staticheck 2018.1 adds a lot more linting-type features, and it looks useful, and I had it tested out a bit while I was poking at the gometalinter interactions with modules, so here's a branch that (1) adds it, (2) also preemptively cleans up a bunch of the lint it reports.

Updates #1640.

## Pull request checklist

- [X] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [X] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [X] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [X] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by seebs** [comment]
So, with module support, "go get" can specify the exact revision of the package to grab, and we could grab the current staticcheck. Until then, if we want to be specific, we'd need to specify the version in the dep stuff. I think the noisiest checks will be off by default in the actual release.

So as-is, this would still run the current pre-module/pre-2018.1 staticcheck, which does less linting but still catches some useful stuff in general. (Conveniently, mostly useful stuff we don't have any problems with.)

There's a handful of pending items it notices, of which one appears to be a PEG artifact we can't trivially get rid of, but we could turn off that warning for that directory. There's also some unused/unexported things in lru/lru.go which we could reasonably comment out if they're not being used.

**Comment by seebs** [comment]
It's the other way, staticcheck is requiring that error strings *don't* start with a capital letter, because that's official Go style, we're just not quite consistent about it.

**Comment by codysoyland** [comment]
Oh, somehow I was reading that diff backwards. Thanks!

**Comment by codysoyland** [comment]
I forgot this PR exists. I guess you're right, this should be closed now.

**Pull request closed without merging**
