### PR TITLE
Group by fixes

### LINKED ISSUE #1800: Calling GroupBy(Rows()) crash the server
### Expected behavior
Server return an error

### Actual behavior
Server crash

### Steps to reproduce the behavior
curl localhost:10101/index/patients/query -X POST -d 'GroupBy(Rows())'

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
MacBook Pro (Retina, 15-inch, Mid 2014), 2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3

### PR DESCRIPTION
**Pull request by jaffee**
## Overview

Add docs for Group By and fix field crash issue. I may try to add Todd's request performance enhancement to this, but it is ready for review as is.

Fixes #1800 and #1801 

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by jaffee** [comment]
nice finds @yuce - I'll look into fixing these

**Comment by jaffee** [comment]
btw, if you wrap `true` in quotes, I think you'll then be able to use that.

**Comment by jaffee** [comment]
pushed a bunch of fixes.

I'm not sure we should actually disallow strings with quotes. It's fairly convenient not to need quotes when experimenting at the command line (no escaping shenanigans).

**Comment by yuce** [comment]
This causes a panic on the server, but not actually break it. Not sure whether we should return an error message:
```
curl -v localhost:10101/index/i1/query -d 'GroupBy(Rows(field=f1, previous=-1, limit=9999999999999999999999999999999999999999999999999999))'
```

**Comment by yuce** [comment]
```
$ curl -v localhost:10101/index/i1/query -d 'GroupBy(Rows(field=f1, limit=9, filter=Rows(field=f12)))'
```
`f12` doesn't exist, but the query above doesn't return an error. Should it ?

**Comment by jaffee** [comment]
you cant filter with a Rows query, so that should error

**Comment by jaffee** [comment]
oh, @yuce you put the filter inside the Rows call, so it just ignores it since it doesn't know that argument.

If you put the filter in the GroupBy it will error.

**Comment by yuce** [comment]
`curl -v localhost:10101/index/i1/query -d 'GroupBy(Rows(field=f1, limit==9999999999999999999999999999999999999999999999999999))'` still causes a panic, but  I think it's better to merge this PR and have a ticket to implement input validation, since this is probably an issue for other calls as well.

**Comment by jaffee** [comment]
agreed

**Pull request merged**
