### PR TITLE
Add QueryResult.Type to protobuf message to distiguish results at the client

### PR DESCRIPTION
**Pull request by travisturner**
## Overview

This PR encodes `Type` with the `QueryResult` protobuf message so that in the case where the client is not able to keep state of the `QueryRequest` the client can correctly handle the result.

TODO:
- [x] add test coverage for `Type`
- [ ] make sure we bump the version for client support

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [x] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by jaffee** [comment]
maybe not worth it, but I wonder if you considered encoding the type as a single byte - in the case where a single request contained many queries, the overhead could actually be substantial I think. We'd do something like 
```go
//go:generate stringer -type=QueryResponseType
type QueryResponseType uint8

const (
	QueryResponseTypeBitmap QueryResponseType = iota
	QueryResponseTypePairs
	QueryResponseTypeSumCount
	QueryResponseTypeUint64
	QueryResponseTypeBool
)
```

and of course change the .proto type.

**Comment by travisturner** [comment]
@jaffee yep, i thought the same thing and already made that change to `iota`

**Comment by jaffee** [comment]
apparently that uses a variable length encoding in protobufs @yuce - I don't know if it would be possible for us to use a smaller type internally though

**Comment by yuce** [comment]
@jaffee That's cool! Since we now have a reliable way of distinguishing between result types, in clients we can have `Result` interface and `results` field of `QueryResponse` can contain `Result`s. So we won't need to store the Type in the client side.

**Pull request merged**
