### PR TITLE
TranslateFile - reopen the same instance

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

## Overview

This PR allows reopen the same instance of `TranslateFile`.
So far, the following test case does not work:
```go
tf := pilosa.NewTranslateFile()

tf.Open()
ids, err := tf.TranslateRowsToUint64(index, field, []string{"val1"})
tf.Close()

tf.Open()
str, err := tf.TranslateRowToString(index, field, ids[0])
tf.Close()

// expected str == "val1"
``` 

In the PR, buffer and read offset are reset in `Close` function, so we can reuse/reopen the same instance of TranslateFile.

### CODE REVIEW

**Comment by jaffee** [comment]
any idea what's up with the dependency changes?

**Comment by kuba--** [comment]
you mean go.* files? this is what happened after i ran `GO111MODULE=on go test`

**Comment by kuba--** [comment]
tried also `go mod tidy`

**Comment by kuba--** [comment]
@jaffee could you take a look. I merged master into the PR, and it's still failing.
```
==================
2019/05/01 12:07:34 [ERR] memberlist: Failed to send gossip to 127.0.0.1:43393: write udp [::]:45693->127.0.0.1:43393: use of closed network connection
2019/05/01 12:07:34 http: translate store read error: pilosa: translate store closed
2019/05/01 12:07:35 [ERR] memberlist: Failed to send gossip to 127.0.0.1:34803: write udp [::]:43393->127.0.0.1:34803: use of closed network connection
--- FAIL: TestNewCluster (0.93s)
```

**Comment by kuba--** [comment]
@jaffee - I've moved `s.n=0` from `Close` to `Open`, and now all tests pass.

**Comment by kuba--** [comment]
@jaffee , @benbjohnson - friendly ping?

**Pull request merged**
