### PR TITLE
Support keys on import CLI -> master

### PR DESCRIPTION
**Pull request by travisturner**
## Overview

I just realized that #1501 was merged into the `develop` branch. I cherry-picked that commit and fixed the merge conflicts. This PR is the merge to master.

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by travisturner** [comment]
There's still an issue with this, so I'm going to hold of on merging this.
The logic here works as long as shard 0 is on the same node as the primary translate store (because all key imports—column key imports, at least—are being sent to shard 0. If, however, shard 0 is located on a secondary translate node, then the `translate store read only` error is returned. We need to address this issue specifically, and also address how best to handle writes to non-primary nodes generally.

**Comment by benbjohnson** [comment]
@travisturner I think we’ll need to have the primary be the coordinator for imports. We could have replicas RPC to the primary for unknown keys too. That might be slow when importing a lot of new keys though. What do you think?

**Comment by travisturner** [comment]
@benbjohnson when you say "be the coordinator" are you referring specifically to `cluster.Coordinator`? I was just looking into the viability of that. It would be nice if we could have the Coordinator node be the primary translate store, and all non-Coordinator nodes stream replica data from the Coordinator. In that case we could get rid of the `translation.primary-url` configuration option.

We would still need to modify the Import logic in the client, but instead of sending columnKey imports to shard 0, we could always send them to the Coordinator.

We would also need to address what happens when the coordinator is changed (i.e. we'd need to modify each node's primary translate store reference).

And finally, there is the case where an import contains columnIDs and rowKeys. I think there, too, we would send those through the Coordinator (for translation).

**Comment by travisturner** [comment]
Yeah, that makes sense that having a single, shared primary doesn't work for replication scaling. What do you think about having each node treat the node before it in the cluster as its primary (with the exception of the primary/coordinator, of course)?

**Comment by travisturner** [comment]
I created issue #1578 to discuss/address this.

**Pull request closed without merging**
