### PR TITLE
WIP: Unexport several names

### PR DESCRIPTION
**Pull request by codysoyland**
## Overview

This branch is the result of a script that unexports everything possible while still passing tests. We need to identify what we want to keep and I will regenerate the PR with those names blacklisted.

This does not currently include subpackages.

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by travisturner** [comment]
I'm going through these now, so I'll leave additional comments, but to start:
I think for the `CacheType*` constants, we should either export all of them or none of them, but not a combination. It seems safe to export constants.

**Comment by codysoyland** [comment]
Just added subpackages.

**Comment by travisturner** [comment]
For subpackages:

It doesn't seem like this is used:
```
Unexport pql.ASSIGN
```

This is a constant, used internally only. I guess just make sure it doesn't rename to `iLLEGAL`.
```
Unexport pql.ILLEGAL
```

This is the stringer method. I don't think it hurts to have stringers defined.
```
Unexport pql.Condition.String
```

These are constants. I don't have a strong opinion on unexporting them.
```
Unexport roaring.ContainerArray
Unexport roaring.ContainerBitmap
Unexport roaring.ContainerRun
Unexport roaring.RunMaxSize
Unexport statsd.BufferLen
Unexport statsd.Prefix
```

**Comment by codysoyland** [comment]
Closing in favor of #1470

**Pull request closed without merging**
